## Машинное обучение 1, ПМИ ФКН ВШЭ

## Практическое домашнее задание 1

### Общая информация

Дата выдачи: 25.01.2026

Мягкий дедлайн: 23:59MSK 08.02.2026

Жесткий дедлайн: 23:59MSK 14.02.2026

### О задании

Задание состоит из двух разделов, посвященных работе с табличными данными с помощью библиотеки `pandas` и визуализации с помощью `matplotlib`. В первом разделе вам предстоит выполнить базовые задания с помощью вышеуказанных библиотек, а во втором распределить студентов по курсам. Баллы даются за выполнение отдельных пунктов. Задачи в рамках одного раздела рекомендуется решать в том порядке, в котором они даны в задании.

Задание направлено на освоение jupyter notebook (будет использоваться в дальнейших заданиях), библиотек pandas и matplotlib.

### Оценивание и штрафы

Каждая из задач имеет определенную «стоимость» (указана в скобках около задачи). Максимально допустимая оценка за работу — 10 баллов без учета бонуса. Сдавать задание после жёсткого дедлайна нельзя.

Задание выполняется самостоятельно. «Похожие» решения считаются плагиатом и все задействованные студенты (в том числе те, у кого списали) не могут получить за него больше 0 баллов (подробнее о плагиате см. на странице курса). Если вы нашли решение какого-то из заданий (или его часть) в открытом источнике, необходимо указать ссылку на этот источник (скорее всего вы будете не единственным, кто это нашел, поэтому чтобы исключить подозрение в плагиате, необходима ссылка на источник).

Устная проверка. Для проверки понимания кода и выводов студент может быть приглашён на устную защиту. Оценка за задание может быть изменена после устной защиты. Если студент не может объяснить ключевые части решения и принятые решения, работа считается недобросовестной и оценивается в 0 баллов независимо от автотестов.

### Формат сдачи

Задания сдаются через систему Anytask. Инвайт можно получить у семинариста или ассистента. Присылать необходимо ноутбук с выполненным заданием. Сам ноутбук называйте в формате `homework-practice-01-pandas-Username.ipynb`, где Username — ваша фамилия.

Для удобства проверки самостоятельно посчитайте свою максимальную оценку (исходя из набора решенных задач) и укажите ниже.

Оценка: xx.

## 0. Введение

Сейчас мы находимся в jupyter-ноутбуке (или ipython-ноутбуке). Это удобная среда для написания кода, проведения экспериментов, изучения данных, построения визуализаций и других нужд, не связанных с написанием production-кода.

Ноутбук состоит из ячеек, каждая из которых может быть либо ячейкой с кодом, либо ячейкой с текстом размеченным и неразмеченным. Текст поддерживает markdown-разметку и формулы в Latex.

Для работы с содержимым ячейки используется *режим редактирования* (*Edit mode*, включается нажатием клавиши **Enter** после выбора ячейки), а для навигации между ячейками используется *командный режим* (*Command mode*, включается нажатием клавиши **Esc**). Тип ячейки можно задать в командном режиме либо с помощью горячих клавиш (**y** to code, **m** to markdown, **r** to edit raw text), либо в меню *Cell -> Cell type*.

После заполнения ячейки нужно нажать *Shift + Enter*, эта команда обработает содержимое ячейки: проинтерпретирует код или сверстает размеченный текст.

In [ ]:
# ячейка с кодом, при выполнении которой появится output
2 + 2

Ячейка с неразмеченным текстом.

Попробуйте создать свои ячейки, написать какой-нибудь код и текст какой-нибудь формулой.

In [ ]:
# your code

[Здесь](https://athena.brynmawr.edu/jupyter/hub/dblank/public/Jupyter%20Notebook%20Users%20Manual.ipynb) находится <s>не</s>большая заметка о используемом языке разметки Markdown. Он позволяет:

0. Составлять упорядоченные списки
1. Выделять *текст* <s>при</s> **необходимости**
2. Добавлять [ссылки](http://imgs.xkcd.com/comics/the_universal_label.png)


* Составлять неупорядоченные списки

Делать вставки с помощью LaTex:
    
$
\left\{
\begin{array}{ll}
x = 16 \sin^3 (t) \\
y = 13 \cos (t) - 5 \cos (2t) - 2 \cos (3t) - \cos (4t) \\
t \in [0, 2 \pi]
\end{array}
\right.$

А ещё можно вставлять картинки, или гифки, или что захотите:

<img src="https://media1.tenor.com/images/9b8fbe9214504bcf6c60fe4e4f7e114e/tenor.gif?itemid=5416416" style="width: 400px">

### Google Colab

Что за колаб?

**Google Colab (Colaboratory)** это **Jupyter Notebook + Cloud + Google Drive.**

Компания Google предоставляет возможность бесплатно запускать ноутбуки (предварительно загрузив их на свой гугл-диск) прямо в облаке. При этом вам не требуется установка никаких пакетов на свою машину, а работать можно прямиком из браузера. Вот ссылка:

https://colab.research.google.com

При использовании вы увидите много сходств с jupyter ноутбуком. Одним из преимуществ является доступность GPU, соответствующую опцию можно активировать в настройках сервиса. При желании вы сможете найти в интернете много туториалов по использованию или разобраться самостоятельно

### Kaggle

Альтернативой является **Kaggle**, он же площадка для самых разных соревнований по машинному обучению

Он, как и колаб, предоставляет бесплатный GPU, и даже не один, с чётким лимитом в 30 часов в неделю (colab может его внезапно отобрать, kaggle - нет) более мощные CPU с большим числом ядер, и больше Гб ОЗУ (раз так в 2.5)

https://www.kaggle.com

К сожалению мир не идеален, недостатки следующие:
- необходимость загружать датасеты через специальную кнопочку
- невозможность использовать свои скрипты и модули :(
- нужно тыкать техподдержку, чтобы создать аккаунт из России

## 1. Табличные данные и Pandas [4 балла]

Pandas - удобная библиотека для работы с табличными данными в Python, если данных не слишком много и они помещаются в оперативную память вашего компьютера. Несмотря на неэффективность реализации и некоторые проблемы, библиотека стала стандартом в анализе данных.

Основной объект в `pandas` - это `pd.DataFrame`, представляющий собой таблицу с именованными колонками различных типов, индексом (может быть многоуровневым). DataFrame можно создавать, считывая таблицу из файла или задавая вручную из других объектов.

В этой части потребуется выполнить несколько небольших заданий. Можно пойти двумя путями: сначала изучить материалы, а потом приступить к заданиям, или же разбираться "по ходу". Выбирайте сами.

Материалы:
1. [Pandas за 10 минут из официального руководства](http://pandas.pydata.org/pandas-docs/stable/10min.html)
2. [Документация](http://pandas.pydata.org/pandas-docs/stable/index.html) (стоит обращаться, если не понятно, как вызывать конкретный метод)
3. [Примеры использования функционала](http://nbviewer.jupyter.org/github/justmarkham/pandas-videos/blob/master/pandas.ipynb)

Многие из заданий можно выполнить несколькими способами. Не существуют единственно верного, но попробуйте максимально задействовать арсенал pandas и ориентируйтесь на простоту и понятность вашего кода. Мы не будем подсказывать, что нужно использовать для решения конкретной задачи, попробуйте находить необходимый функционал сами (название метода чаще всего очевидно). В помощь вам документация, поиск и StackOverflow.

In [1]:
%pylab inline
import pandas as pd
import numpy as np

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib

<span style="color:red">Перед выполнением задания необходимо ознакомиться с первым семинаром (seminars/sem01-pandas.ipynb) </span>.

Это поможет вам получить общее понимание происходящего и успешнее справиться с заданием.

Также успешному выполнению способствует внимательное чтение текста задания от начала до конца.

Удачи!

Скачаем подготовленные на семинаре данные:

In [2]:
!wget  -O 'end_seminar.xlsx' -q 'https://www.dropbox.com/scl/fi/2ezfw6b3y1umremflbgdl/end_seminar.xlsx?rlkey=xzecol82ybnpu0eon0b1s11pp&st=f45sugvp&dl=0'

"wget" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
"st" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
"dl" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.

Для пользователей Windows: скачайте файл самостоятельно и поместите его в папку с тетрадкой. Или попробуйте один из следующих вариантов:

In [ ]:
# !powershell iwr -outf somefile https://somesite/somefile

In [ ]:
# !pip install wget
# import wget
# wget.download('https://www.dropbox.com/scl/fi/2ezfw6b3y1umremflbgdl/end_seminar.xlsx?rlkey=xzecol82ybnpu0eon0b1s11pp&st=f45sugvp&dl=0', 'end_seminar.xlsx')

##### В первой части задания (до раздела "Распределение студентов по курсам") запрещены циклы (`for`, `while`) и построчные преобразования: `apply`/`applymap`, `map`, `assign` с `lambda`, `np.vectorize`, `np.apply_along_axis` и аналогичные конструкции. Нарушение этого правила повлечёт снижение оценки. Используйте векторные операции и стандартные методы pandas.

Для каждой задачи из этого раздела вы должны написать код для получения ответа, а также дать текстовый ответ, если он предполагается.

На некоторые вопросы вы можете получить путём пристального взгляда на таблицу, но это не будет засчитываться. Вы в любом случае должны получить ответ с помощью кода.

#### 1. [0.5 баллов] Откройте файл с таблицей (не забудьте про её формат). Выведите 3 последних строки.

Посмотрите на данные и скажите, что они из себя представляют, сколько в таблице строк, какие столбцы? (на это не надо отвечать, просто подумайте об этом)

In [2]:
df = pd.read_excel('end_seminar.xlsx')
df[-3:]

,timestamp,id,rating,group_22,is_mi,fall_1,fall_2,fall_3,spring_1,spring_2,spring_3,is_first_time,percentile,group_21,blended,is_ml_student
426,2024-08-19 11:49:43.000,77b2b19d26b7f160c1938369197f7cac590b2e0cfcac3b...,1232,NaN,NaN,Принятие решений в условиях риска и неопределе...,Основы разработки компьютерных игр,Введение в платформы данных,Теория и практика онлайн-экспериментов,Конфликты и кооперация (преподается на английс...,Децентрализованные системы,Да,0.440252,212.0,Соревновательный анализ данных,NaN
427,2024-08-13 14:58:30.000,6dafd9a56d08aeb419166d314b0cd6f3107ae5e8dbd636...,961,NaN,NaN,Основы информационного поиска,Дизайн систем,Язык программирования Scala,Промышленное программирование на Haskell,Методы сжатия и передачи медиаданных,Децентрализованные системы,Да,0.858491,215.0,Безопасность систем на базе LLM,NaN
428,2024-08-13 18:35:25.235,4bf710d7b89064e1a3cbcc69b7ca67c20d6181dc72ad35...,1374,NaN,NaN,Трансформерные и мультимодальные модели,Глубинное обучение для текстовых данных,Self-supervised Learning,Обучение с подкреплением,Современные языковые модели,Развёртывание ML-моделей в высоконагруженных с...,Да,0.169811,217.0,Продуктовый подход к анализу данных,NaN

### Ответьте на вопросы:
1. Сколько было уникальных пользователей из групп 22-го года набора, а сколько из групп 21-го года?

In [3]:
df["id"].nunique()

418

In [4]:
print(f'21 год набора: {len(pd.unique(df[df["group_21"].notna()]["id"]))}')
print(f'22 год набора: {len(pd.unique(df[df["group_22"].notna()]["id"]))}')

21 год набора: 159
22 год набора: 259

2. Есть ли среди объединенного множества 3-го и 4-го курса уникальные студенты с равными перцентилями?

In [6]:
df["id"].nunique() - df["percentile"].nunique() > 0

True

#### 2. [0.5 балла] Есть ли в данных пропуски? В каких колонках? Сколько их в каждой из этих колонок?

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 429 entries, 0 to 428
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   timestamp      429 non-null    datetime64[ns]
 1   id             429 non-null    object
 2   rating         429 non-null    int64
 3   group_22       270 non-null    float64
 4   is_mi          26 non-null     float64
 5   fall_1         429 non-null    object
 6   fall_2         429 non-null    object
 7   fall_3         429 non-null    object
 8   spring_1       381 non-null    object
 9   spring_2       381 non-null    object
 10  spring_3       381 non-null    object
 11  is_first_time  429 non-null    object
 12  percentile     429 non-null    float64
 13  group_21       159 non-null    float64
 14  blended        159 non-null    object
 15  is_ml_student  175 non-null    float64
dtypes: datetime64[ns](1), float64(5), int64(1), object(9)
memory usage: 53.8+ KB

In [8]:
missing = df.isna().sum()
missing[missing > 0]

group_22         159
is_mi            403
spring_1          48
spring_2          48
spring_3          48
group_21         270
blended          270
is_ml_student    254
dtype: int64

Заполните пропуски пустой строкой для строковых колонок, нулём для числовых и False для булевых (постарайтесь избежать перечисления названий всех столбцов). Опирайтесь не на смысл столбцов, а на текущий тип данных.

In [9]:
df[df.dtypes[df.dtypes == dtype('O')].index] = df[df.dtypes[df.dtypes == dtype('O')].index].fillna("")
df[df.dtypes[df.dtypes == dtype('int64')].index] = df[df.dtypes[df.dtypes == dtype('int64')].index].fillna(0)
df[df.dtypes[df.dtypes == dtype('float64')].index] = df[df.dtypes[df.dtypes == dtype('float64')].index].fillna(0.0)
df[df.dtypes[df.dtypes == dtype('bool')].index] = df[df.dtypes[df.dtypes == dtype('bool')].index].fillna(False)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 429 entries, 0 to 428
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   timestamp      429 non-null    datetime64[ns]
 1   id             429 non-null    object
 2   rating         429 non-null    int64
 3   group_22       429 non-null    float64
 4   is_mi          429 non-null    float64
 5   fall_1         429 non-null    object
 6   fall_2         429 non-null    object
 7   fall_3         429 non-null    object
 8   spring_1       429 non-null    object
 9   spring_2       429 non-null    object
 10  spring_3       429 non-null    object
 11  is_first_time  429 non-null    object
 12  percentile     429 non-null    float64
 13  group_21       429 non-null    float64
 14  blended        429 non-null    object
 15  is_ml_student  429 non-null    float64
dtypes: datetime64[ns](1), float64(5), int64(1), object(9)
memory usage: 53.8+ KB

In [12]:
df.sample(5)

,timestamp,id,rating,group_22,is_mi,fall_1,fall_2,fall_3,spring_1,spring_2,spring_3,is_first_time,percentile,group_21,blended,is_ml_student
277,2024-08-14 19:02:34,85cc073a9d0fc028bc28360976d39c0c2205131f9cf68d...,1122,0.0,0.0,Глубинное обучение в обработке звука,Байесовские методы в машинном обучении,Глубинное обучение для текстовых данных,Обучение с подкреплением,Эффективные системы глубинного обучения,Современные языковые модели,Да,0.603774,215.0,Введение в дифференциальную геометрию,1.0
80,2024-08-14 16:20:33,7935540b095acdf82e4baf21202af7afaf27e4ec193766...,437,224.0,0.0,Основы тензорных вычислений,Statistical Learning Theory,Функциональное программирование,Стохастический анализ,Генеративные модели в машинном обучении (углуб...,Машинное обучение 2,Да,0.933333,0.0,,1.0
126,2024-08-12 00:10:52,2ab682d14b59d373439d0c102092e2f9e7e9a72d970e8a...,554,224.0,0.0,Системы баз данных,Системы баз данных,Системы баз данных,Компьютерные сети,Компьютерные сети,Компьютерные сети,Да,0.612963,0.0,,0.0
427,2024-08-13 14:58:30,6dafd9a56d08aeb419166d314b0cd6f3107ae5e8dbd636...,961,0.0,0.0,Основы информационного поиска,Дизайн систем,Язык программирования Scala,Промышленное программирование на Haskell,Методы сжатия и передачи медиаданных,Децентрализованные системы,Да,0.858491,215.0,Безопасность систем на базе LLM,0.0
139,2024-08-11 23:13:30,967fea9751524e4b246a0c7bc800e2e385ed4de1e24474...,538,227.0,0.0,Системы баз данных,Разработка микросервисов на Go,Распределенные системы,Компьютерные сети,Промышленное программирование на языке Java,Машинное обучение 2,Да,0.662963,0.0,,0.0

#### 3. [0.5 балла] Посмотрите повнимательнее на колонку 'is_first_time'.

Каково процентное соотношение ответов? Сколько из них "Нет"?

In [13]:
df["is_first_time"].value_counts()

is_first_time
Да     407
Нет     22
Name: count, dtype: int64

In [15]:
df["is_first_time"].value_counts() / len(df)

is_first_time
Да     0.948718
Нет    0.051282
Name: count, dtype: float64

Если вы найдете повторные обращения студентов, оставьте только самую позднюю версию. В дальнейших заданиях используйте версию данных без повторов. Уберите колонку is_mi, она нам не пригодится

<i>Обращения со значением "Нет" в 'is_first_time' могут быть как повторными, так и первичными, поскольку поле заполняли сами студенты.</i>

In [16]:
df = df.sort_values("timestamp").drop_duplicates("id", keep="last")

In [20]:
df = df.drop(columns=["is_mi"])

#### 4. [0.5 балла] Какие  blended-курсы для четверокурсников существуют? На какой blended-курс записалось наибольшее количество студентов? На каком из blended-курсов наименьший средний перцентиль студентов, подавших заявку (выведите этот курс и количество студентов на нем)?

In [28]:
df[df["group_21"] > 0]["blended"].value_counts()

blended
Протоколы доказательств с нулевым разглашением    44
ML System Design                                  38
Соревновательный анализ данных                    26
Продуктовый подход к анализу данных               25
Введение в дифференциальную геометрию             13
Безопасность систем на базе LLM                   13
Name: count, dtype: int64

Больше всего записалось на курс "Протоколы доказательств с нулевым разглашением".

In [29]:
g = df[df["group_21"] > 0].groupby("blended")["percentile"].aggregate(np.mean)
g.index[g.argmin()]

C:\Users\grach\AppData\Local\Temp\ipykernel_30196\3084602378.py:1: FutureWarning: The provided callable <function mean at 0x000001A1FD3175B0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  g = df[df["group_21"] > 0].groupby("blended")["percentile"].aggregate(np.mean)

'Продуктовый подход к анализу данных'

In [30]:
df[df["group_21"] > 0]["blended"].value_counts()[g.index[g.argmin()]]

25

#### 5. [1 балл] Выясните, есть ли студенты с абсолютно одинаковыми предпочтениями по всем курсам.

Для этого сформируйте таблицу, где для каждого возможного набора курсов посчитано количество студентов, выбравших такой набор, и оставьте только строки где это количество больше 1. Формировать варианты, которые не представлены ни одним студентом изначально, не требуется.

В данном случае набор курсов задается упорядоченным множеством ('fall_1', 'fall_2', 'fall_3', 'spring_1', 'spring_2', 'spring_3', 'blended'). Элемент blended будет нулевым для 3-го курса.

In [59]:
df["combination"] = df[["fall_1", "fall_2", "fall_3", "spring_1", "spring_2", "spring_3", "blended"]].apply(
    lambda row: set(row), axis=1
)

In [61]:
df["combination"].value_counts().to_frame()

                                                    count
combination
{, Компьютерные сети, Системы баз данных}               9
{, Распределенные системы, Компьютерные сети, С...      4
{, Компьютерные сети, Операционные системы 2, С...      3
{Децентрализованные системы, Дизайн систем, Мет...      3
{, Аналитика данных, Компьютерные сети, Системы...      2
...                                                   ...
{, Statistical Learning Theory, Генеративные мо...      1
{, Безопасность компьютерных систем, Генеративн...      1
{Децентрализованные системы, Методы сжатия и пе...      1
{, Компьютерные сети, Операционные системы 2, С...      1
{Безопасность компьютерных систем, Децентрализо...      1

[381 rows x 1 columns]

Студенты с одинаковыми предпочтениями существуют

In [56]:
df = df.drop(columns=["combination"])

#### 6. [0.5 балла] Найдите курсы по выбору, на которые записывались как студенты 22-го года набора, так и студенты 21-го года.

In [ ]:
# your code

Методом исключения найдите курсы, которые предлагались только студентам 22-го года и только студентам 21-го года.

In [ ]:
# your code

Видите ли вы что-то необычное в получившихся списках? (менять ничего не нужно, просто подумайте)

**Ответ:**

### Визуализации и matplotlib

При работе с данными часто неудобно делать какие-то выводы, если смотреть на таблицу и числа в частности, поэтому важно уметь визуализировать данные. Здесь будут описаны ключевые правила оформления графиков для **всех** домашних заданий.

У matplotlib, конечно же, есть [документация](https://matplotlib.org/users/index.html) с большим количеством [примеров](https://matplotlib.org/examples/), но для начала достаточно знать про несколько основных типов графиков:
- plot — обычный поточечный график, которым можно изображать кривые или отдельные точки;
- hist — гистограмма, показывающая распределение некоторой величины;
- scatter — график, показывающий взаимосвязь двух величин;
- bar — столбцовый график, показывающий взаимосвязь количественной величины от категориальной.

В этом задании вы попробуете построить один из них. Не забывайте про базовые принципы построения приличных графиков:
- оси должны быть подписаны, причём не слишком мелко;
- у графика должно быть название;
- если изображено несколько графиков, то необходима поясняющая легенда;
- все линии на графиках должны быть чётко видны (нет похожих цветов или цветов, сливающихся с фоном);
- если отображена величина, имеющая очевидный диапазон значений (например, проценты могут быть от 0 до 100), то желательно масштабировать ось на весь диапазон значений (исключением является случай, когда вам необходимо показать малое отличие, которое незаметно в таких масштабах);
- сетка на графике помогает оценить значения в точках на глаз, это обычно полезно, поэтому лучше ее отрисовывать;
- если распределение на гистограмме имеет тяжёлые хвосты, лучше использовать логарифмическую шкалу.

Еще одна библиотека для визуализации: [seaborn](https://jakevdp.github.io/PythonDataScienceHandbook/04.14-visualization-with-seaborn.html) (обычно сокращается до sns). Это настройка над matplotlib, иногда удобнее и красивее делать визуализации через неё.

**5 пунктов после которых ваши графики не будут прежними:**
- для красивой картинки <code>%config InlineBackend.figure_format = 'retina'</code>
- задаем размер (почти) всех графиков (можно выбрать другие значения) <code>plt.rcParams['figure.figsize'] = 8, 5</code>
- размер шрифта подписей графиков <code>plt.rcParams['font.size'] = 12</code>
- формат в котором сохраняется изображение <code>plt.rcParams['savefig.format'] = 'pdf'</code>
- sns – seaborn, добавляет решетку <code>sns.set_style('darkgrid')</code>

Добавьте эти функции в ячейку ниже. Каждый график все равно придется настраивать отдельно, но указанные строчки позволят значительно упростить процесс.

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

# your code

#### 7. [0.5 балла] Постройте график (barplot) медианных перцентилей в зависимости от первого символа hex-кода id студента

Таким образом мы на глаз прикидываем, есть ли зависимость между, якобы, случайным id и значимым параметром. Если зависимость есть, и в дальнейшем мы будем сплитовать данные на тест и трейн по такому айдишнику без перемешивания, то можем допустить утечку, поэтому такие особенности важно отслеживать.

В графике явно задайте порядок столбцов по символам hex-алфавита (от 0 до f слева направо) и настройте отображение доверительных интервалов уровня **0.96**. Можно ли говорить о наличии проверяемой зависимости на основе визуальной информации?

In [ ]:
# your code

Сохраните график в формате pdf (так он останется векторизованным).

In [ ]:
# your code

## 2. Распределение студентов по курсам. (6 баллов + один бонусный балл)

#### **<span style="color:red">‼️ВНИМАТЕЛЬНО ИЗУЧИТЕ ТЕКСТ НИЖЕ‼️</span>.**

<span style="color:orange">Если во время выполнения заданий у вас возникнут вопросы - еще раз перечитайте текст целиком, скорее всего ответы уже содержатся в нем.</span>

Теперь вам нужно распределить студентов по осенним курсам по выбору, учитывая их предпочтения.

## **Алгоритм распределения студентов по курсам**:

1. Для каждой дисциплины формируется список тех, кто указал её первым приоритетом (если студент должен выбрать два курса по выбору, то для него дисциплины, которые он указал первым и вторым приоритетом, рассматриваются как дисциплины первого приоритета). Если желающих больше, чем мест (см ниже), то выбирается топ по перцентилю рейтинга.
2. На дисциплинах, где остались места после первой волны, формируются списки тех, кто выбрал их вторым приоритетом, и места заполняются лучшими по перцентилю рейтинга студентами. После этого проводится такая же процедура для дисциплин третьего приоритета.
3. Если студент не попал на необходимое количество курсов по итогам трёх волн, с ним связывается учебный офис и решает вопрос в индивидуальном порядке.

## ☝️ **Обращаем ваше внимание на следующие детали:**

### Особенности реализации алгоритма:

- Конкурс на каждый курс общий для 3-го (22-й год) и 4-го курса (21-й год), то есть список формируется из студентов обоих курсов.

- По умолчанию на каждой дисциплине по выбору у 3 и 4 курсов может учиться 1 группа (до 30 студентов).
  - Исключения:
    * Количественные финансы - 60
    * Промышленное программирование на Haskell - 60
    * Рекомендательные системы - 60
    * Глубинное обучение в обработке звука - 1000 (да да, не удивляйтесь! раньше и не такое было...)


- По умолчанию студент выбирает один осенний и один весенний курс по выбору, а также четверокурсники выбирают один blended-курс. Студенты групп **21-го года специализации МОП** выбирают по 2 осенних и 2 весенних курса по выбору. <i>Для студентов, которые выбирают 2 курса (например, осенних) первый приоритет — <code>fall_1</code> и <code>fall_2</code>, второй приоритет — <code>fall_3</code>. Такие студенты участвуют только в двух волнах отбора</i>.

- Студенты специализации МОП не могут выбрать весенним курсом по выбору Машинное обучение 2. Если студент специализации МОП выбрал Машинное обучение 2, то его приоритеты сдвигаются.
  - "Сдвиг" = приоритеты 2 и 3 становятся приоритетами 1 и 2, 3-й приоритет остается пустым.
  - Из-за совпадений первого и второго курса по выбору в прочих случаях двигать приоритеты не надо.


- Blended-курсы не трогайте, по ним не надо распределять, на другие курсы они никак не влияют.

- В рамках своего решения вы можете считать, что в процессе распределения не возникнет ситуации, когда на одно место претендуют студенты с одинаковым перцентилем.

### Я МОП и я люблю <s>Я</s>



**Принадлежность к <s> стойлу</s> специализации МОП определяется так:**

- 21-й год (4-й курс):
  * 211, 212, 213 - МОП; остальные - не МОП! 👎

- 22-й год (3-й курс)
  -  Студенты, у которых проставлен флаг в колонке `is_ml_student`.

### Рейтинг и перцентиль

#### Рейтинг

В столбце `'rating'` записана кредитно-рейтинговая сумма студента (грубо говоря, сумма оценок студента по всем его дисциплинам с весами (веса > 1) — чем дольше шла дисциплина, тем больше вес; подробности тут: https://www.hse.ru/studyspravka/rate/).

Чем больше курсов взял студент за период обучения, и чем лучше он их закрыл, тем выше его значение `'rating'`, соответственно, эта метрика возрастает по "качеству" студента.

#### Перцентиль

В столбце `'percentile'` записан перцентиль студента в рамках своего курса своей ОП.

Перцентиль студента X определяется следующим образом: "процент студентов, чьи результаты обучения лучше, чем у студента X". Соответственно, 0% -- лучший студент на потоке, $\to$ 100% -- худший студент на потоке, то есть метрика убывает по "качеству" студента.


Мы распределяем студентов по топу перцентиля, то есть по наименьшему перцентилю.


За прочими подробностями отправляем вас в ноутбук семинара.

### Требования к решению

- Постарайтесь воздержаться от использования циклов там, где это возможно. <i> Допустимо итерироваться по <b>курсам</b>, на которые проводится отбор, и по <b>волнам</b> отбора. Если вы придумаете, как обойтись без цикла по курсам, то можете получить **+1 бонусный балл** к итоговой оценке. <b>Дублирование кода не признается успешным избавлением от циклов</b></i>

- На выходе ожидается файл `res_fall.csv` с результатами распределения на осенние курсы по выбору. Файл должен быть следующего формата:

    * три столбца: ID, course1, course2
    
    * Если студент не попал на курс, но должен был, то вместо названия курса в ячейке должна быть строка "???"
    
    * Если студент должен выбрать только один курс, то в колонке course2 для него должна стоять строка "-"

    * Если студент должен выбрать два курса по выбору, то порядок в колонках course1 и course2 не важен.
    
    * Формат csv: для сохранения воспользуйтесь `df.to_csv("res_fall.csv", index=False)`

Для работы вам могут понадобиться следующие данные:

- Результаты опроса (вы уже использовали этот файл в первой части задания, но на всякий случай ссылка: https://www.dropbox.com/scl/fi/2ezfw6b3y1umremflbgdl/end_seminar.xlsx?rlkey=xzecol82ybnpu0eon0b1s11pp&st=f45sugvp&dl=0)


Кстати, убедитесь, что в данных больше нет пропусков, повторных записей и лишних колонок

#### 0. Проверка

Для начала давайте убедимся, что вы успешно выполнили задания первой части и проверим ваши данные на наличие пропусков и повторов:

In [ ]:
assert df.shape == (418, 15), 'В таблице остались повторы или потеряны данные'
assert df.isna().sum().sum() == 0, 'В таблице остались пропуски'

Если вы не получили AssertionError, то можете продолжать.

#### 1. [1 балл] Создайте новый признак, обозначающий, сколько осенних курсов должен выбрать студент

В этом вам может помочь информация о специализации и группе студента.

In [ ]:
# (￣^￣)ゞ

Проверка:

In [ ]:
col_name = '' # insert your new column name as str

assert(df[df['id'] == 'bcca318e644999583156ff3ab9de3d6bd02295dcb166e39006568ffe9582207b'][col_name] == 1).all()
assert(df[df['id'] == 'edb64996c64421378537d941a77426a5a7bd84f9967ad9f523ca61386e5469ed'][col_name] == 1).all()
assert(df[df['id'] == '5f96908e3ce5d84d693ddd79670d60cd1c6a02646aa779f46586a7699dda7c25'][col_name] == 1).all()
assert(df[df['id'] == '0f137538a170b64258c0e10839cadc325e5f22fc5bb5fa9e20b7351f0a680366'][col_name] == 2).all()

#### 2. [2 балла] Распределите студентов в соответствии с первым приоритетом

In [ ]:
# (￣^￣)ゞ

Сверьте назначенные вами на первой волне курсы с эталоном. Для этого преобразуйте данные о назначенных курсах, приведя их в разрез "по студенту" (подробнее см в докстринге тест-функции), и передайте в функцию 'check_first_wave_assignments'. Если функция не выбросила Exception, то всё хорошо!

**Обратите внимание: здесь обрабатывать детали условия касающиеся ответов `'???'` и `'-'` из требований к решению
обрабатывать не нужно!**

Трансформацию датасета (создание колонок `'course1'` и `'course2'`) советуем выделить в отдельную функцию, поскольку она понадобится вам далее при сдаче результатов в тестирующую систему.

In [ ]:
!wget  -O 'task_2_check.csv' -q 'https://www.dropbox.com/scl/fi/mxmp3b8ecssaei78sk4sp/task_2_check.csv?rlkey=uccmkaeo0zgv78pp3czs0s122&st=gr7s4m5u&dl=0'
check_df = pd.read_csv('./task_2_check.csv')

Если открытие check_df кинуло Exception, проверьте, что файл лежит в той же директории, из которой запущено ядро (kernel) вашего ноутбука (в его current working directory).

*Стандартно файл должен скачиваться как раз туда, но вдруг у вас что-то пошло не так*

In [ ]:
from pandas.testing import assert_frame_equal
from collections import Counter

def check_first_wave_assignments(assignments: pd.DataFrame) -> None:
    """
    assignments - pandas DataFrame с колонками ['ID', 'course1', 'course2', 'fall_course_num']. Одна строка -- один студент.
    - 'ID' - id студента (не объект индекса!)
    - 'course1', 'course2' - названия курсов, назначенные студенту в первую волну.
    Если один из курсов не назначен (вне зависимости от того, должен ли был быть назначен), то None.
    - 'fall_course_num' - число осенних курсов, которые должен выбрать студент.
    """

    def course_columns_to_set_column(row: pd.DataFrame):
        result = Counter()


        for column in ['course1', 'course2']:
            if (not pd.isna(row[column]) and row[column] is not None):
                result[row[column]] += 1

        return result


    ANSWER_SOURCE = './task_2_check.csv'

    ALTERNATIVES = {
        "cdb87f7b15495e514eb481230b44540c6b0cfeb347c991f06b1e361fcdef0c0b": [
            Counter({"Глубинное обучение для текстовых данных", "Байесовские методы в машинном обучении"}),
            Counter({"Глубинное обучение для текстовых данных", }),
        ],
        "6fa015d8846e21f4f79bac013b469a1e6e962fffd6121b4d9bcde3906275293e": [
            Counter({"Statistical Learning Theory", }),
            Counter({"Statistical Learning Theory", "Байесовские методы в машинном обучении"}),
        ]
    }

    answer_df = pd.read_csv(ANSWER_SOURCE)


    assignments = assignments.copy()


    assignments['course_set'] = assignments.apply(course_columns_to_set_column, axis=1)

    answer_df['course_set'] =  answer_df.apply(course_columns_to_set_column, axis=1)



    answer_df_common = answer_df[~answer_df['ID'].isin(ALTERNATIVES.keys())][['ID', 'course_set', 'fall_course_num']]

    assignments_common = assignments[~assignments['ID'].isin(ALTERNATIVES.keys())][['ID', 'course_set', 'fall_course_num']]

    answer_df_common = answer_df_common.set_index('ID').sort_index()
    assignments_common = assignments_common.set_index('ID').sort_index()


    assert_frame_equal(answer_df_common, assignments_common, check_dtype=False, check_names=False)

    for student in ALTERNATIVES:
        assert assignments[assignments['ID'] == student]['course_set'].isin(ALTERNATIVES[student]).iloc[0]
        assert answer_df[answer_df['ID'] == student]['fall_course_num'].iloc[0] == assignments[assignments['ID'] == student]['fall_course_num'].iloc[0]

#### 3. [2 балла] Проведите все три волны отбора студентов на курсы по выбору

In [ ]:
# (￣^￣)ゞ

**Отправьте свой файл res_fall.csv в [Я.контест](https://new.contest.yandex.ru/contests/89154/start) и прикрепите/укажите ниже ваш никнейм и id успешной посылки.**

*Дисклеймер:*

Успешная посылка в контесте является **обязательным** условием получения полного балла за этот (и следующий) пункт. Если добиться успешной посылки не удастся, баллы будут выставляться на усмотрение проверяюшего.

При этом ОК в контесте не гарантирует полный балл. Оценка всё равно может быть снижена в случае обнаружения неэффективностей или ошибок в коде. Если вы сдадите в AnyTask очевидно неработающий код или ноутбук без кода, но при этом в контест будет сдан корректный файл, то это будет расцениваться как плагиат.

На всякий случай просим вас сдать вместе с ноутбуком файл res_fall.csv в anytask

### 4. [1 балла] Распределите таким же образом студентов еще и на весенние курсы по выбору.

Если ваш код был хорошо структурирован, то это не составит проблем.

Если вы выполнили это задание, сдайте среди прочего файл res_spring.csv в таком же формате, как и res_fall.csv.

In [ ]:
# (￣^'￣)ゞ

**Отправьте свой файл res_spring.csv в [Я.контест](https://new.contest.yandex.ru/contests/89154/start) и прикрепите/укажите ниже ваш никнейм и id успешной посылки.**

На всякий случай просим вас сдать вместе с ноутбуком файл res_spring.csv в anytask, **туда же и продублируйте никнейм в Я.контесте и id успешных посылок**.

Вставьте картинку, описывающую ваш опыт выполнения этого задания: